parameters:
  - name: SolutionBaseName
    type: string
  - name: BuildConfiguration
    type: string
    default: 'Release'

jobs:
  - job: Build_iOS
    displayName: 'Build iOS Application'
    pool:
      vmImage: 'macOS-latest'
    steps:
      - template: azure-pipelines-templates/build/step/ios-app-build.yml@das-platform-building-blocks
        parameters:
          WorkspacePath: 'src/My Apprenticeship App/My Apprenticeship App.xcodeproj'
          SchemeName: 'My Apprenticeship App'
          ArtifactName: '${{ parameters.SolutionBaseName }}'
