parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: BuildiOSApp
  displayName: Build iOS MAUI App
  pool:
    vmImage: 'macOS-latest'
    workspace:
      clean: all
  variables:
  - group: BUILD Management Resources
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks
  - template: azure-pipelines-templates/build/step/ios-app-build.yml@das-platform-building-blocks
    parameters:
      ContinueOnVulnerablePackageScanError: true  
  
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: '$(AppleCertificate)'
      certPwd: '$(iOSCertPassword)'
      keychain: 'temp'

  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install app store provisioning profile'
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '$(ProvisioningProfile)'


  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish iOS'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/MyApprenticeship.sln'
      arguments: '-f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:EnableAssemblyILStripping=false -p:RuntimeIdentifier=ios-arm64'
      zipAfterPublish: false

  - task: CopyFiles@2
    displayName: 'Copy iOS artifact'
    inputs:
      Contents: '**/*.ipa'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      OverWrite: true
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'