parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  pool:
    vmImage: 'macOS-latest'
    workspace:
      clean: all
  variables:
  - group: BUILD Management Resources
  steps:
  - task: InstallAppleCertificate@2
    displayName: Install Apple Certificate
    inputs:
      certSecureFile: 'CGCertificates.p12'
      certPwd: '$(CertPassword)'
      keychain: 'temp'
      removeCertsAfterBuild: true

  - task: InstallAppleProvisioningProfile@1
    displayName: Install Provisioning Profile
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'My_Apprenticeship_Pilot.mobileprovision'

  - task: Bash@3
    displayName: Verify Installed Certificates
    inputs:
      targetType: 'inline'
      script: |
        echo "Installed Certificates:"
        security find-identity -v -p codesigning

  - task: Bash@3
    displayName: Verify Installed Provisioning Profiles
    inputs:
      targetType: 'inline'
      script: |
        echo "Installed Provisioning Profiles:"
        /usr/bin/profiles -C -v

  - task: Bash@3
    displayName: Publish iOS App
    inputs:
      targetType: 'inline'
      script: |
        dotnet publish src/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.csproj \
          -f net8.0-ios -c ${{ parameters.BuildConfiguration }} \
          -p:SigningIdentity="Apple Distribution" \
          -p:ProvisioningProfile="My_Apprenticeship_Pilot.mobileprovision"

  - task: CopyFiles@2
    displayName: Copy artifacts
    inputs:
      Contents: |
        azure/**
        **/*.ipa
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifact
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)/publish
      ArtifactName: ${{ parameters.SolutionBaseName }}
