default_platform(:ios)

platform :ios do
  desc "Build the iOS application"
  lane :build_only do |options|
    workspace_path = options[:workspace_path]
    scheme_name = options[:scheme_name]
    build_number = options[:build_number]

    setup_ci

    match(type: "appstore", readonly: true)

    gym(
      workspace: workspace_path,
      scheme: scheme_name,
      clean: true,
      export_method: "app-store",
      output_directory: "./output",
      output_name: "ApprenticeshipApp.ipa",
      xcargs: "CURRENT_PROJECT_VERSION=#{build_number}"
    )
  end

  desc "Upload the IPA to TestFlight or App Store"
  lane :upload_ipa do |options|
    ipa_path = options[:ipa_path]
    release_notes = options[:release_notes]
    target = ENV['DistributionTarget']

    if target == 'AppStore'
      deliver(
        ipa: ipa_path,
        release_notes: { 'default' => release_notes },
        submit_for_review: false,
        automatic_release: false,
        force: true,
        skip_screenshots: true,
        skip_metadata: false
      )
    else
      pilot(
        ipa: ipa_path,
        changelog: release_notes,
        skip_submission: true,
        distribute_external: false
      )
    end
  end
end
